server:
  port: 7000
spring:
  application:
    name: lc-auth-center

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 30 #该字段代表每ns像服务器发送一次心跳
    lease-expiration-duration-in-seconds: 90  #该字段代表如果ns内没有接收到客户端发过来的心跳，则会从实例中清除掉这个实例
  client:
    serviceUrl:
      defaultZone: http://lc.eureka.com:8761/eureka/,http://lc.eureka.com:8762/eureka/
#info需要显示的信息
info:
  app.name: lc-auth-center
  company.name: www.chenglezheng.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

#自定义属性值
access_token:
  store-jwt: true
  jwt-signing-key: cheng@le@zheng=$==+_+%0%:)(:)
  add-user-info: false


hystrix:
   command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillseconds: 60000 #线程超时,调用Fallback方法
      circuitBreaker:
        requestVolumeThreshold: 3 #10秒内出现3个以上请求(已临近阀值),并且出错率在50%以上,开启断路器.断开服务,调用Fallback方法

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
  hystrix :
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always